- tools/striker-manage-install-target
> * Typo fixed in striker-manage-install-target insertion variable.

- Anvil/Tools.pm
- Anvil/Tools/DRBD.pm
- Anvil/Tools/Get.pm
- scancore-agents/scan-drbd/scan-drbd
- scancore-agents/scan-drbd/scan-drbd.xml
- scancore-agents/scan-server/scan-server
- scancore-agents/scan-server/scan-server.xml
- share/words.xml
- tools/anvil-provision-server
- tools/test.pl
Some work outside strings included in this PR
> String bugs

- Anvil/Tools/Get.pm
> * Updated the os_type regex to detect CentOS Stream properly.

- anvil.spec.in
> Make sure that firewalld is started before trying to opening ports

- anvil.spec.in
> Fix make srpm/make rpm BuildRequires for mock based environments

- tools/anvil-configure-host
- tools/anvil-join-anvil
- tools/striker-auto-initialize-all
- tools/striker-initialize-host
> * Removed debug logging from tools.

- anvil.spec.in
- tools/Makefile.am
> testing: distribute striker auto setup tool outside of normal PATH

- anvil.spec.in
- tools/Makefile.am
> build: move striker-auto-initialize-all to proper location

- anvil.spec.in
> anvil-daemon: fix Requires:

- tools/striker-initialize-host
> * Fixed a bug that caused striker-initialize-host to not compile / run.

- anvil.spec.in
- tools/striker-manage-install-target
> Update to kmod-drbd91

- Anvil/Tools/Convert.pm
- Anvil/Tools/Database.pm
- Anvil/Tools/Log.pm
- Anvil/Tools/ScanCore.pm
- Anvil/Tools/System.pm
- Anvil/Tools/Words.pm
- html/jquery-ui-1.12.1/package.json
- notes
- scancore-agents/scan-cluster/scan-cluster
- scancore-agents/scan-cluster/scan-cluster.xml
- scancore-agents/scan-ipmitool/scan-ipmitool
- share/anvil.sql
- share/words.xml
- tools/anvil-daemon
- tools/anvil-delete-server
- tools/anvil-provision-server
- tools/anvil-safe-stop
- tools/scancore
- tools/striker-purge-host
> * Fixed a bug where the log message for a changed CIB wasn't useful.

- Anvil/Tools/DRBD.pm
- Anvil/Tools/Database.pm
> * Fixed a missing semi-colon that broke Database.pm.

- cgi-bin/set_power
- share/words.xml
Making this a draft PR until "special merge instructions" are discussed.
> Web UI: make `set_power` endpoint functional

- cgi-bin/set_membership
- share/words.xml
Making this a draft PR until "special merge instructions" are discussed.
> Web UI: make `set_membership` endpoint functional

- cgi-bin/get_memory
The reserved memory constant will be changed from 64GiB to 8GiB.
This PR will be ready once #111 gets merged and issues/8 branch is rebased to updated master.
> Web UI: correct reserved memory constant

- anvil.spec.in
> Add workaround for rsync usage

- tools/anvil-daemon
- tools/anvil-manage-power
- tools/anvil-update-system
> * Added more logging while chasing a function test bug.

- tools/anvil-configure-host
> * Added an explicit delete call when network changes.

- Anvil/Tools/Network.pm
- share/words.xml
- tools/anvil-configure-host
* Updated anvil-configure-host to not reboot on network chane (will verify when this commit is function tested).
> * Finished updating Network->check_network() to check/heal bridges.

- tools/anvil-configure-host
> * Re-enabled reboot

- tools/anvil-daemon
> * Fixed a typo that blocked anvil-daemon from starting.

- Anvil/Tools/Network.pm
> * Clear out the bond health in Network->check_network().

- tools/anvil-daemon
> * Disabling the periodic network health check in anvil-daemon.

- anvil.spec.in
- tools/striker-manage-install-target
> Switch to kmod-drdb

- tools/anvil-provision-server
> Switched default graphics for new servers to 'vnc' instead of spice.

- cgi-bin/get_networks
> Web UI: correct typo in network bond link speed comparison

- Anvil/Tools/System.pm
- notes
- tools/anvil-join-anvil
> Fixed a bug where corosync's configuration of a backup ring was broken.

- Anvil/Tools/Alert.pm
- Anvil/Tools/Database.pm
- scancore-agents/scan-network/scan-network
- share/words.xml
- tools/striker-db-report
This is an important PR and should be rolled out to all active systems as soon as possible.
> Anvil tools dev

- anvil.spec.in
fix installation on c9s and does not break earlier versions
> [spec] drop unnecessary Requires

- anvil.spec.in
> spec: update Requires to deal with rhel-9 cloud images

- Anvil/Tools/Storage.pm
- scancore-agents/scan-ipmitool/scan-ipmitool
- tools/anvil-manage-files
> Bumped 'Exhaust Temp' jump threshold to 30c in scan-ipmitool.

- Anvil/Tools/Get.pm
- man/striker-initialize-host.8
- share/words.xml
- tools/anvil-manage-files
- tools/striker-initialize-host
* Updated striker-initialize-host to support calls from command line switches, and wrote the man page for it.
> * Updated Get->switches() to always support job-uuid.

- anvil.spec.in
> Update NM requirements to pull in ifup/down on fresh installs

- anvil.spec.in
Remove call to anvil-version-change from rpm %post as it´s a DB corruptor trigger
> Partially revert e9f390b65b5a5db75d43d949c773fd69b31307b8

- striker-ui-api/src/lib/buildCondition.ts
- striker-ui-api/src/lib/request_handlers/host/buildQueryHostDetail.ts
- striker-ui-api/src/lib/request_handlers/host/getHost.ts
- striker-ui-api/src/lib/request_handlers/network-interface/getNetworkInterface.ts
- striker-ui-api/src/routes/network-interface.ts
- striker-ui-api/src/types/HostOverview.d.ts
- striker-ui/components/Display/Preview.tsx
- striker-ui/components/NetworkInitForm.tsx
- striker-ui/components/OutlinedLabeledInputWithSelect.tsx
- striker-ui/components/PrepareNetworkForm.tsx
- striker-ui/components/ProvisionServerDialog.tsx
- striker-ui/components/SelectWithLabel.tsx
- striker-ui/components/StrikerConfig/AddPeerDialog.tsx
- striker-ui/components/Tab.tsx
- striker-ui/components/TabContent.tsx
- striker-ui/components/Tabs.tsx
- striker-ui/components/Text/BodyText.tsx
- striker-ui/hooks/useProtectedState.ts
- striker-ui/lib/buildObjectStateSetterCallback.ts
- striker-ui/lib/getQueryParam.ts
- striker-ui/pages/manage-element/index.tsx
- striker-ui/pages/prepare-network/index.tsx
- striker-ui/types/APIHost.d.ts
- striker-ui/types/PrepareNetworkForm.d.ts
- striker-ui/types/SelectWithLabel.d.ts
- striker-ui/types/TabContent.d.ts
- striker-ui/types/Tabs.d.ts
This PR adds 1) the prepare network form for nodes and DR hosts, and 2) the page that connects the management of non-striker components.
> Add prepare network form and connector page

- share/words.xml
- tools/anvil-provision-server
IMPORTANT:
the virt-install change will need to be tested via web UI as well, to see if the console to the VM being deployed works.
It works fine in CI / command-line and virt-install exits immediately after spawning the right bits into libvirt.
> Minor fixes

- Anvil/Tools.pm
- Anvil/Tools/Database.pm
- man/anvil-change-password.8
- man/anvil-manage-server-storage.8
- share/words.xml
- tools/anvil-manage-server-storage
This adds jobs support to anvil-manager-server-storage. This addresses issue #352
> Manage storage ready for web-ui

- Anvil/Tools/Database.pm
- Anvil/Tools/Network.pm
- Anvil/Tools/Server.pm
- scancore-agents/scan-ipmitool/scan-ipmitool
- scancore-agents/scan-server/scan-server
- scancore-agents/scan-server/scan-server.xml
- share/words.xml
This fixes several issues with scan-server
> Fix scan server

- Anvil/Tools/Server.pm
- man/anvil-shutdown-server.8
- share/words.xml
- tools/anvil-shutdown-server
> Add force off

- striker-ui-api/src/lib/request_handlers/anvil/buildAnvilSummary.ts
- striker-ui-api/src/lib/request_handlers/anvil/getAnvilCpu.ts
- striker-ui-api/src/lib/request_handlers/anvil/getAnvilStore.ts
- striker-ui-api/src/types/ApiAn.d.ts
- striker-ui/components/Anvils/AnvilSummary.tsx
- striker-ui/components/Anvils/AnvilSummaryList.tsx
- striker-ui/components/Bars/AllocationBar.tsx
- striker-ui/components/Bars/BorderLinearProgress.tsx
- striker-ui/components/Bars/ProgressBar.tsx
- striker-ui/components/Bars/StackBar.tsx
- striker-ui/components/Bars/Underline.tsx
- striker-ui/components/Bars/index.tsx
- striker-ui/components/Files/ManageFilePanel.tsx
- striker-ui/components/Memory.tsx
- striker-ui/lib/api_converters/index.ts
- striker-ui/lib/api_converters/toAnvilDetail.ts
- striker-ui/lib/api_converters/toAnvilMemoryCalcable.ts
- striker-ui/lib/api_converters/toAnvilOverviewHostList.ts
- striker-ui/lib/api_converters/toAnvilOverviewList.ts
- striker-ui/lib/api_converters/toAnvilSharedStorageOverview.ts
- striker-ui/pages/index.tsx
- striker-ui/types/APIAnvil.d.ts
- striker-ui/types/AnvilSummary.d.ts
- striker-ui/types/StackBar.d.ts
This PR **doesn't** update the web related builds; they will be updated in the next patch(es).
Closes #442
> Web UI: add node list to dashboard

- cgi-bin/set_power
- man/anvil-manage-host.8
- man/striker-boot-machine.8
- share/words.xml
- tools/anvil-manage-host
- tools/striker-boot-machine
* Wrote the man page for striker-boot-machine, changing --host-name to --host, and adding the '--host all' support.
* Updated anvil-manage-host to support checking/enabling/disabling network mapping mode.
> Updated striker-boot-machine to support booting all machines.

- Anvil/Tools/Database.pm
- Anvil/Tools/Remote.pm
- Anvil/Tools/ScanCore.pm
- Anvil/Tools/Server.pm
- share/words.xml
- tools/anvil-configure-host
- tools/anvil-daemon
- tools/anvil-delete-server
- tools/anvil-manage-files
- tools/anvil-manage-host
- tools/anvil-manage-server-system
- tools/anvil-provision-server
* If the call to Remote-call() set the target that was actually the local short hostname, it would fail to make the call at all. Now if the 'target' is local, the shell call is instead passed to System->call() instead.
* Cleaned up logging.
> Fixed a bug in Remote->call()

- scancore-agents/scan-ipmitool/scan-ipmitool
- scancore-agents/scan-network/scan-network
* Increased logging to scan-ipmitool and scan-network to help trace a duplicate DB entry bug.
> Fixed a bug in scan-ipmitool that was causing duplicate history entries

- Anvil/Tools/System.pm
- share/words.xml
- tools/Makefile.am
- tools/striker-collect-debug
- units/anvil-daemon.service
- units/scancore.service
DO NOT MERGE YET. Striker debug log collection currently forces secure logging.
> Bumped logging to debug striker-collect-debug

- striker-ui/components/Files/AddFileForm.tsx
Note: this PR doesn't include a rebuild; it will be included in the next PR.
Closes #488
> Web UI: adjust messages during file uploads

- Anvil/Tools/Cluster.pm
- man/Makefile.am
- share/words.xml
- tools/anvil-join-anvil
> Upgrade tools

- tools/striker-collect-debug
> striker-collect-debug: fix collection of cib.xml

- selinux/Makefile.am
use proper autotool way to install / uninstall files
> build: fix make distcheck as user vs root

- Anvil/Tools.pm
- Anvil/Tools/Email.pm
- anvil.spec.in
- tools/anvil-manage-alerts
> Migrate from `mailx` to `s-nail` on RHEL/Almalinux >= 9

- Anvil/Tools/Database.pm
- Anvil/Tools/Remote.pm
- tools/striker-update-cluster
This is a PR to try to track / resolve occasional hangs / timeouts when updating peer machines in the cluster.
> Fix rare hang when updating peers

- Anvil/Tools/Remote.pm
- man/anvil-manage-keys.1
- share/words.xml
- tools/anvil-manage-keys
This makes it easier for checking/updating a rebuilt machine's system ssh keys.
> Add support for 'anvil-check-keys --test'

- scancore-agents/scan-cluster/scan-cluster
- tools/anvil-manage-dr
Also added another attribute to be muted in scan-cluster when parsing the CIB.
> Changed '--list' to '--show' to match the man page.

- Anvil/Tools/Database.pm
- Anvil/Tools/Network.pm
- man/anvil-configure-host.8
- share/words.xml
- tools/anvil-configure-host
- tools/anvil-join-anvil
- tools/anvil-provision-server
* Also added support for connecting bridges to interfaces instead of bonds. This adds support for DR hosts without bonds and MicroAnvil! subnodes.
> Updated anvil-configure-host to support text config.

- Anvil/Tools/Storage.pm
- anvil.spec.in
- man/anvil-manage-server-network.8
- share/words.xml
- tools/anvil-manage-files
- tools/anvil-manage-server-network
- tools/striker-get-screenshots
Not needed given install target function not used
> More back-end work

- Anvil/Tools/Remote.pm
- tools/anvil-manage-keys
- tools/striker-initialize-host
* This is to handle rebuilding a machine in the cluster.
> Updated striker-initialize-host to remove old host keys

- Anvil/Tools.pm
- Anvil/Tools/Database.pm
- README.md
- share/anvil.sql
- tools/anvil-daemon
- tools/anvil-version-changes
* This is done to save the Striker WebUI from having to make SSH calls to query qemu capabilities.
* Created Database->insert_or_update_host_variable() and fixed bugs in the host_variables schema.
> Added caching of subnode and DR host qemu capability caching.

- Anvil/Tools/Server.pm
- man/anvil-shutdown-server.8
- scancore-agents/scan-server/scan-server
- share/words.xml
- tools/anvil-delete-server
- tools/anvil-shutdown-server
This PR should resolve issues #632
> Beta fixes

- share/words.xml
- tools/anvil-manage-server-system
> Improved too-many-core error messages.

- anvil.spec.in
> Web UI: restart API on RPM package update

- Anvil/Tools/Job.pm
- Anvil/Tools/Network.pm
- Anvil/Tools/Server.pm
- man/anvil-shutdown-server.8
- scancore-agents/scan-server/scan-server
- scancore-agents/scan-server/scan-server.xml
- share/words.xml
- tools/anvil-join-anvil
- tools/anvil-manage-keys
- tools/anvil-manage-storage-groups
- tools/anvil-pull-pid-logs
- tools/anvil-safe-start
- tools/anvil-shutdown-server
* Closes issue #859 
* Closes issue #860 
* Closes issue #848
> Improved handling of rebuild hosts

- Anvil/Tools/Validate.pm
- share/words.xml
- tools/anvil-delete-server
- tools/anvil-relocate-server
> Fixes server deletion issue

- Anvil/Tools/Network.pm
- man/anvil-manage-dr.8
- share/words.xml
- tools/anvil-daemon
- tools/anvil-join-anvil
- tools/anvil-manage-dr
- tools/striker-initialize-host
ports opened on the proper zone.
> Fixed a bug where DR hosts using the BCN weren't having their firewall

- Anvil/Tools/Server.pm
- share/words.xml
connecting to libvirtd.
This should resolves issue #897
> Changed Remote->add_target_to_known_hosts to ->test_access when

- Anvil/Tools.pm
- scancore-agents/scan-drbd/scan-drbd
- scancore-agents/scan-drbd/scan-drbd.xml
- share/words.xml
- tools/anvil-manage-dr
- tools/anvil-safe-start
> Prevent unlinking of DR from node while servers still protected

- striker-ui/package-lock.json
- striker-ui/package.json
Closes #906 
Closes #907 
Closes #908 
Closes #909
> Web UI: bump axios `1.7.4->1.8.2`, @babel/helpers `7.17.2->7.27.1`, @babel/runtime `7.23.7->7.27.1`, next `14.2.23->14.2.28` in `/striker-ui`

- share/words.xml
- tools/anvil-join-anvil
Made an explicit check in anvil-join-anvil to see if the SN1 or MN1 network exists before trying to test access.
> Improved support for microAnvil! systems.

- Anvil/Tools/Network.pm
- Anvil/Tools/System.pm
- tools/anvil-daemon
Patch for #920 , not closing until verified.
> Web UI: patch 920 (websockify recovery)
